# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from crazyflie_msgs/PrioritizedControl.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import crazyflie_msgs.msg

class PrioritizedControl(genpy.Message):
  _md5sum = "6383d540d010819be07756f19814ef1f"
  _type = "crazyflie_msgs/PrioritizedControl"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Control control
float64 priority
================================================================================
MSG: crazyflie_msgs/Control
float64 roll
float64 pitch
float64 yaw_dot
float64 thrust"""
  __slots__ = ['control','priority']
  _slot_types = ['crazyflie_msgs/Control','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       control,priority

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PrioritizedControl, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.control is None:
        self.control = crazyflie_msgs.msg.Control()
      if self.priority is None:
        self.priority = 0.
    else:
      self.control = crazyflie_msgs.msg.Control()
      self.priority = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5d().pack(_x.control.roll, _x.control.pitch, _x.control.yaw_dot, _x.control.thrust, _x.priority))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.control is None:
        self.control = crazyflie_msgs.msg.Control()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.control.roll, _x.control.pitch, _x.control.yaw_dot, _x.control.thrust, _x.priority,) = _get_struct_5d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5d().pack(_x.control.roll, _x.control.pitch, _x.control.yaw_dot, _x.control.thrust, _x.priority))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.control is None:
        self.control = crazyflie_msgs.msg.Control()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.control.roll, _x.control.pitch, _x.control.yaw_dot, _x.control.thrust, _x.priority,) = _get_struct_5d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5d = None
def _get_struct_5d():
    global _struct_5d
    if _struct_5d is None:
        _struct_5d = struct.Struct("<5d")
    return _struct_5d
