// Generated by gencpp from file crazyflie_msgs/FlagPosition.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_MSGS_MESSAGE_FLAGPOSITION_H
#define CRAZYFLIE_MSGS_MESSAGE_FLAGPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crazyflie_msgs
{
template <class ContainerAllocator>
struct FlagPosition_
{
  typedef FlagPosition_<ContainerAllocator> Type;

  FlagPosition_()
    : flag(false)
    , x(0.0)
    , y(0.0)  {
    }
  FlagPosition_(const ContainerAllocator& _alloc)
    : flag(false)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _flag_type;
  _flag_type flag;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::crazyflie_msgs::FlagPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazyflie_msgs::FlagPosition_<ContainerAllocator> const> ConstPtr;

}; // struct FlagPosition_

typedef ::crazyflie_msgs::FlagPosition_<std::allocator<void> > FlagPosition;

typedef boost::shared_ptr< ::crazyflie_msgs::FlagPosition > FlagPositionPtr;
typedef boost::shared_ptr< ::crazyflie_msgs::FlagPosition const> FlagPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazyflie_msgs::FlagPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazyflie_msgs::FlagPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crazyflie_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'crazyflie_msgs': ['/home/eecs149_rst/final_project_workspace/src/crazyflie_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie_msgs::FlagPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie_msgs::FlagPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyflie_msgs::FlagPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyflie_msgs::FlagPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie_msgs::FlagPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie_msgs::FlagPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazyflie_msgs::FlagPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b02003392a7ba348a106356014b2f67a";
  }

  static const char* value(const ::crazyflie_msgs::FlagPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb02003392a7ba348ULL;
  static const uint64_t static_value2 = 0xa106356014b2f67aULL;
};

template<class ContainerAllocator>
struct DataType< ::crazyflie_msgs::FlagPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazyflie_msgs/FlagPosition";
  }

  static const char* value(const ::crazyflie_msgs::FlagPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazyflie_msgs::FlagPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool flag\n\
float64 x\n\
float64 y\n\
";
  }

  static const char* value(const ::crazyflie_msgs::FlagPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazyflie_msgs::FlagPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FlagPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazyflie_msgs::FlagPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crazyflie_msgs::FlagPosition_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAZYFLIE_MSGS_MESSAGE_FLAGPOSITION_H
