// Generated by gencpp from file crazyflie_msgs/PrioritizedControl.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_MSGS_MESSAGE_PRIORITIZEDCONTROL_H
#define CRAZYFLIE_MSGS_MESSAGE_PRIORITIZEDCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <crazyflie_msgs/Control.h>

namespace crazyflie_msgs
{
template <class ContainerAllocator>
struct PrioritizedControl_
{
  typedef PrioritizedControl_<ContainerAllocator> Type;

  PrioritizedControl_()
    : control()
    , priority(0.0)  {
    }
  PrioritizedControl_(const ContainerAllocator& _alloc)
    : control(_alloc)
    , priority(0.0)  {
  (void)_alloc;
    }



   typedef  ::crazyflie_msgs::Control_<ContainerAllocator>  _control_type;
  _control_type control;

   typedef double _priority_type;
  _priority_type priority;





  typedef boost::shared_ptr< ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator> const> ConstPtr;

}; // struct PrioritizedControl_

typedef ::crazyflie_msgs::PrioritizedControl_<std::allocator<void> > PrioritizedControl;

typedef boost::shared_ptr< ::crazyflie_msgs::PrioritizedControl > PrioritizedControlPtr;
typedef boost::shared_ptr< ::crazyflie_msgs::PrioritizedControl const> PrioritizedControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crazyflie_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'crazyflie_msgs': ['/home/eecs149_rst/149finalproject/final_project_workspace/src/crazyflie_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6383d540d010819be07756f19814ef1f";
  }

  static const char* value(const ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6383d540d010819bULL;
  static const uint64_t static_value2 = 0xe07756f19814ef1fULL;
};

template<class ContainerAllocator>
struct DataType< ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazyflie_msgs/PrioritizedControl";
  }

  static const char* value(const ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Control control\n\
float64 priority\n\
================================================================================\n\
MSG: crazyflie_msgs/Control\n\
float64 roll\n\
float64 pitch\n\
float64 yaw_dot\n\
float64 thrust\n\
";
  }

  static const char* value(const ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control);
      stream.next(m.priority);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PrioritizedControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crazyflie_msgs::PrioritizedControl_<ContainerAllocator>& v)
  {
    s << indent << "control: ";
    s << std::endl;
    Printer< ::crazyflie_msgs::Control_<ContainerAllocator> >::stream(s, indent + "  ", v.control);
    s << indent << "priority: ";
    Printer<double>::stream(s, indent + "  ", v.priority);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAZYFLIE_MSGS_MESSAGE_PRIORITIZEDCONTROL_H
